#!/bin/bash
export TWITTER_NLP=/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp
echo Doing 'ASTRO File Manager with Cloud'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/ASTRO File Manager with Cloud-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/ASTRO File Manager with Cloud-pos.txt'
echo Doing 'Air Call-Accept free (Necta)'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Air Call-Accept free (Necta)-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Air Call-Accept free (Necta)-pos.txt'
echo Doing 'AntiVirus Security - FREE'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/AntiVirus Security - FREE-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/AntiVirus Security - FREE-pos.txt'
echo Doing 'Audible for Android'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Audible for Android-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Audible for Android-pos.txt'
echo Doing 'Battle.net Authenticator'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Battle.net Authenticator-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Battle.net Authenticator-pos.txt'
echo Doing 'Best Apps Market - for Android'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Best Apps Market - for Android-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Best Apps Market - for Android-pos.txt'
echo Doing 'Burger'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Burger-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Burger-pos.txt'
echo Doing 'Camera illusion'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Camera illusion-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Camera illusion-pos.txt'
echo Doing 'Camera magic'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Camera magic-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Camera magic-pos.txt'
echo Doing 'Cardiograph'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Cardiograph-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Cardiograph-pos.txt'
echo Doing 'ColorNote Notepad Notes'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/ColorNote Notepad Notes-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/ColorNote Notepad Notes-pos.txt'
echo Doing 'Craigs Race'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Craigs Race-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Craigs Race-pos.txt'
echo Doing 'DiDi - Free Calls & Texts'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/DiDi - Free Calls & Texts-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/DiDi - Free Calls & Texts-pos.txt'
echo Doing 'Face Mood Scanner'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Face Mood Scanner-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Face Mood Scanner-pos.txt'
echo Doing 'Funny Call'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Funny Call-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Funny Call-pos.txt'
echo Doing 'Funny Camera'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Funny Camera-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Funny Camera-pos.txt'
echo Doing 'Glympse - Share GPS location'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Glympse - Share GPS location-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Glympse - Share GPS location-pos.txt'
echo Doing 'HeyTell'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/HeyTell-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/HeyTell-pos.txt'
echo Doing 'Hootsuite (Social Media Mgmt)'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Hootsuite (Social Media Mgmt)-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Hootsuite (Social Media Mgmt)-pos.txt'
echo Doing 'Job Search'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Job Search-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Job Search-pos.txt'
echo Doing 'LED Scroller 3 - FREE'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/LED Scroller 3 - FREE-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/LED Scroller 3 - FREE-pos.txt'
echo Doing 'Little Girl Magic'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Little Girl Magic-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Little Girl Magic-pos.txt'
echo Doing 'Mobile Hidden Camera'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Mobile Hidden Camera-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Mobile Hidden Camera-pos.txt'
echo Doing 'My Days - Period & Ovulation â¢'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/My Days - Period & Ovulation â¢-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/My Days - Period & Ovulation â¢-pos.txt'
echo Doing 'My Tracks'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/My Tracks-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/My Tracks-pos.txt'
echo Doing 'Noom CardioTrainer'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Noom CardioTrainer-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Noom CardioTrainer-pos.txt'
echo Doing 'Note Everything'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Note Everything-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Note Everything-pos.txt'
echo Doing 'Opera Mini â Fast web browser'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Opera Mini â Fast web browser-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Opera Mini â Fast web browser-pos.txt'
echo Doing 'OvuView: Ovulation & Fertility'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/OvuView: Ovulation & Fertility-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/OvuView: Ovulation & Fertility-pos.txt'
echo Doing 'Parking King'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Parking King-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Parking King-pos.txt'
echo Doing 'Parking Manijak'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Parking Manijak-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Parking Manijak-pos.txt'
echo Doing 'Race 2 Free'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Race 2 Free-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Race 2 Free-pos.txt'
echo Doing 'Raging Thunder 2 - FREE'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Raging Thunder 2 - FREE-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Raging Thunder 2 - FREE-pos.txt'
echo Doing 'Rebtel: Cheap and Free Calls'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Rebtel: Cheap and Free Calls-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Rebtel: Cheap and Free Calls-pos.txt'
echo Doing 'SMS Popup'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/SMS Popup-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/SMS Popup-pos.txt'
echo Doing 'SoundHound'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/SoundHound-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/SoundHound-pos.txt'
echo Doing 'Text-To-Speech Extended'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Text-To-Speech Extended-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Text-To-Speech Extended-pos.txt'
echo Doing 'TiKL Touch Talk Walkie Talkie'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/TiKL Touch Talk Walkie Talkie-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/TiKL Touch Talk Walkie Talkie-pos.txt'
echo Doing 'Unblock Parking Jam - Free'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Unblock Parking Jam - Free-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Unblock Parking Jam - Free-pos.txt'
echo Doing 'WikiMobile (Wikipedia Browser)'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/WikiMobile (Wikipedia Browser)-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/WikiMobile (Wikipedia Browser)-pos.txt'
echo Doing 'Zello PTT Walkie-Talkie'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Zello PTT Walkie-Talkie-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Zello PTT Walkie-Talkie-pos.txt'
