#!/bin/bash
export TWITTER_NLP=/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp
echo Doing 'ASTRO File Manager with Cloud'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/ASTRO File Manager with Cloud-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/ASTRO File Manager with Cloud-pos.txt'
echo Doing 'Air Call-Accept free (Necta)'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Air Call-Accept free (Necta)-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Air Call-Accept free (Necta)-pos.txt'
echo Doing 'Antarctic Adventure Free'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Antarctic Adventure Free-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Antarctic Adventure Free-pos.txt'
echo Doing 'Call Dispatcher'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Call Dispatcher-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Call Dispatcher-pos.txt'
echo Doing 'Call-Timer'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Call-Timer-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Call-Timer-pos.txt'
echo Doing 'Calming Music to Tranquilize'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Calming Music to Tranquilize-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Calming Music to Tranquilize-pos.txt'
echo Doing 'Cardiograph'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Cardiograph-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Cardiograph-pos.txt'
echo Doing 'DiDi - Free Calls & Texts'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/DiDi - Free Calls & Texts-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/DiDi - Free Calls & Texts-pos.txt'
echo Doing 'Easy Browser'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Easy Browser-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Easy Browser-pos.txt'
echo Doing 'Fast Food Calorie Counter'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Fast Food Calorie Counter-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Fast Food Calorie Counter-pos.txt'
echo Doing 'File Browser'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/File Browser-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/File Browser-pos.txt'
echo Doing 'Finger Dance Pro'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Finger Dance Pro-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Finger Dance Pro-pos.txt'
echo Doing 'Floating Browser'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Floating Browser-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Floating Browser-pos.txt'
echo Doing 'Fun Cinemas'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Fun Cinemas-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Fun Cinemas-pos.txt'
echo Doing 'Fun Math Tricks Lite'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Fun Math Tricks Lite-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Fun Math Tricks Lite-pos.txt'
echo Doing 'Funny Call'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Funny Call-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Funny Call-pos.txt'
echo Doing 'Keys Jumper Adventure'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Keys Jumper Adventure-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Keys Jumper Adventure-pos.txt'
echo Doing 'Music Therapy for Refreshment'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Music Therapy for Refreshment-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Music Therapy for Refreshment-pos.txt'
echo Doing 'My Days - Period & Ovulation â?¢'
echo Doing 'My Tracks'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/My Tracks-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/My Tracks-pos.txt'
echo Doing 'Noom CardioTrainer'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Noom CardioTrainer-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Noom CardioTrainer-pos.txt'
echo Doing 'Opera Mini â?? Fast web browser'
echo Doing 'OvuView: Ovulation & Fertility'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/OvuView: Ovulation & Fertility-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/OvuView: Ovulation & Fertility-pos.txt'
echo Doing 'Phone2Phone Internet Calling'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Phone2Phone Internet Calling-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Phone2Phone Internet Calling-pos.txt'
echo Doing 'Rebtel: Cheap and Free Calls'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Rebtel: Cheap and Free Calls-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Rebtel: Cheap and Free Calls-pos.txt'
echo Doing 'Santa Fun Jokes'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Santa Fun Jokes-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Santa Fun Jokes-pos.txt'
echo Doing 'Street Dancer Deluxe Free'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Street Dancer Deluxe Free-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Street Dancer Deluxe Free-pos.txt'
echo Doing 'Stretch Exercises'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Stretch Exercises-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/Stretch Exercises-pos.txt'
echo Doing 'WikiMobile (Wikipedia Browser)'
cat '/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/WikiMobile (Wikipedia Browser)-prepos.txt' | python /Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/libs/twitter_nlp/python/ner/extractEntities2.py --pos --chunk >>'/Users/bansal/Desktop/current/NLP_PROJECT/DBUGR/data/POS/WikiMobile (Wikipedia Browser)-pos.txt'
